import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import Head from 'next/head';
import Header from './components/header';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'selling',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
